config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'adventures#index'

  resources :adventures do
    resources :scenes
  end

  resources :admin_users, controller: 'users'
  resources :check_ins, only: [:new, :create, :destroy]

  get 'statistics' => 'statistics#index'
  get 'statistics/sex_pie' => 'statistics#sex_chart'
  get 'statistics/virgin_pie' => 'statistics#virgin_chart'
  get 'statistics/age_chart' => 'statistics#age_chart'
  

end

app/models/user.rb
require "concerns/zero_id_fix.rb"
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :check_ins

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # supposed to be temporary
  include ZeroOidFix

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :character_name,    type: String
  field :first_name,        type: String
  field :last_name,         type: String
  field :sex,               type: String, default: 'Other'
  field :age,               type: Integer
  field :first_time,       type: Boolean, default: true

  validates_presence_of :first_name, :last_name
  validates_inclusion_of :sex, in: ['M', 'F', 'Other']
  after_create :add_default_role

  def role
    if self.has_role? :admin
      "admin"
    elsif self.has_role :character
      "character"
    else
      "player"
    end
  end

  private

  def add_default_role
    self.add_role :player if self.roles.blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @list = User.all.order_by(:character_name.asc).entries
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = 'password'
    if @user.valid?
      if params[:user][:first_time] == "1"
        @user.first_time = true
      elsif params[:user][:first_time] == "0"
        @user.first_time = false
      end
      @user.add_role(params[:user][:roles].to_sym)
      @user.save
    else
      redirect_to(new_admin_user_path) and return
    end
    redirect_to(admin_users_path) and return
  end

  def show
    @user = User.where(id: params[:id]).first
  end

  def destroy
    @user = User.where(id: params[:id]).first
    @user.delete
    redirect_to admin_users_path
  end

  def edit
    @user = User.where(id: params[:id]).first
  end

  def update
    @user = User.where(id: params[:id]).first
    redirect_to root_path and return if @user.nil?
    if @user.update_attributes(user_params)
      if params[:user][:first_time] == "1"
        @user.first_time = true
      elsif params[:user][:first_time] == "0"
        @user.first_time = false
      end
      @user.roles = []
      @user.add_role(params[:user][:roles].to_sym)
      @user.save ? (redirect_to(admin_users_path) and return) : (redirect_to(admin_users_path, notice: 'An Error occured ') and return)
    else
      redirect_to(admin_users_path, notice: 'An Error occured ') and return
    end
  end

  private
  def user_params
    params.require(:user).permit(:character_name, :first_name, :last_name, :email, :sex, :age, :first_time?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit User</h2>
<%= form_for @user, url: {action: "update"} do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name, class: 'form-control' %> <br>
<%= f.label :last_name %>
<%= f.text_field :last_name, class: 'form-control' %> <br>
<%= f.label :character_name %>
<%= f.text_field :character_name, class: 'form-control' %> <br>
<%= f.label :email %>
<%= f.text_field :email, class: 'form-control' %> <br>
<%= f.label :password %>
<small><em>Password must be at least 8 letters long</em></small><br>
<%= f.password_field :password, class: "form-control" %><br>
<%= f.label :first_time, "First Timer?" %>
<%= f.check_box :first_time %><br>
<%= f.label :sex %>
<%= f.select(:sex, options_for_select(['M', 'F', 'Other']), {}, {class: 'form-control', value: "#{@user.sex}"}) %><br>
<%= f.label :age %><br>
<%= f.select(:age, (13..100), {}, {class: 'form-control', value: "#{@user.age}"}) %><br>
<%= f.label :roles, "Role" %>
<%= f.select(:roles, options_for_select([['player', 'player'], ['character', 'character'], ['admin', 'admin']]), {}, {class: 'form-control'}) %><br>
<%= f.submit 'Edit', class: 'btn btn-success' %>
<% end %>

app/views/users/index.html.erb
<h2><i class="glyphicon glyphicon-user"></i> Users</h2>
<%= link_to "+Create User", new_admin_user_path, class: "btn btn-success" %>
<br>
<table class="table table-hover">
  <th>Character name</th>
  <th>First name</th>
  <th>Last name</th>
  <th>Roles</th>
  <th>Actions</th>
  <% @list.each do |u| %>
    <tr>
      <td>
        <%= u.character_name %>
      </td>
      <td>
        <%= u.first_name %>
      </td>
      <td>
        <%= u.last_name %>
      </td>
      <td>
          <% u.roles.each do |r| %>
            <%= "#{r.name} " %>
          <% end %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_user_path(u), class: 'btn btn-xs btn-info' %>
        <%= link_to "Delete", admin_user_path(u), method: :delete, class: 'btn btn-xs btn-danger' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h2>Create a User</h2>
<%= form_for :user, url: {action: "create"} do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: 'form-control' %> <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: 'form-control' %> <br>
  <%= f.label :character_name %>
  <%= f.text_field :character_name, class: 'form-control' %> <br>
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %> <br>
  <%= f.label :first_time, "First Timer?" %>
  <%= f.check_box :first_time %><br>
  <%= f.label :sex %>
  <%= f.select(:sex, options_for_select(['M', 'F', 'Other']), {}, {class: 'form-control'}) %><br>
  <%= f.label :age %><br>
  <%= f.select(:age, (13..100), {}, {class: 'form-control'}) %><br>
  <%= f.label :roles, "Role" %>
  <%= f.select(:roles, options_for_select([['player', 'player'], ['character', 'character'], ['admin', 'admin']]), {}, {class: 'form-control'}) %><br>
  <%= f.submit 'Create', class: 'btn btn-success' %>
<% end %>