config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'adventures#index'

  resources :adventures do
    resources :scenes
  end

  resources :admin_users, controller: 'users'
  resources :check_ins, only: [:new, :create, :destroy]

  get 'statistics' => 'statistics#index'
  get 'statistics/sex_pie' => 'statistics#sex_chart'
  get 'statistics/virgin_pie' => 'statistics#virgin_chart'
  get 'statistics/age_chart' => 'statistics#age_chart'
  

end

app/models/adventure.rb
class Adventure
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :scenes

  field :name,      type: String
  field :tagline,   type: String
  field :synopsis,  type: String

  validates_presence_of :name

  after_create :initiate_death

  protected

  def initiate_death
    death = Scene.create(title: "Death", adventure_id: self.id)
  end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :authenticate_user!

  def index
    @list = Adventure.all.entries
    @users = User.all.entries
  end

  def create
    a = Adventure.new name: params[:adventure][:name], tagline: params[:adventure][:tagline], synopsis: params[:adventure][:synopsis]
    a.save ? redirect_to(root_path) : redirect_to(new_adventure_path)
  end

  def new
    @adventure = Adventure.new()
  end

  def edit
    @adventure = Adventure.where(:id => params[:id]).first
    render 'edit'
  end

  def update
    adventure = Adventure.where(:id => params[:id]).first
    if adventure.nil?
      redirect_to adventures_path
    else
      if adventure.update_attributes(adventure_params)
        redirect_to adventures_path(id: adventure.id)
      else
        redirect_to edit_adventures_path(id: adventure.id)
      end
    end
  end

  def show
    @adventure = Adventure.where(id: params[:id]).first
    @scenes = @adventure.scenes
  end

  def destroy
    if Adventure.where(id: params[:id]).delete
      redirect_to adventures_path
    else
      redirect_to adventures_path, notice: 'An error occured'
    end
  end

  private

  def adventure_params
    params.require(:adventure).permit(:name, :tagline, :synopsis)
  end

end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/edit.html.erb
<%= form_for @adventure , url: { action: "update" } do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, class: "form-control" %>
  <br>
  <%= f.label :tagline %>:
  <%= f.text_field :tagline, class: "form-control" %>
  <br>
  <%= f.label :synopsis %>:
  <%= f.text_area :synopsis, class: "form-control" %>
  <br>
  <%= f.submit "Update", class: "btn btn-success" %>
<% end %>

app/views/adventures/index.html.erb
<div class='container'>
  <h2><i class="glyphicon glyphicon-tower"></i> Adventures</h2>

  <%= link_to "Create Adventure", new_adventure_path, class: 'btn btn-success' %>

  <%= link_to "Users", admin_users_path, class: "btn btn-success" %>

  <%= link_to "Statistics", statistics_path, class: "btn btn-warning" %>

  <table class='table table-hover'>
    <% @list.each do |a| %>
      <td><%= link_to a.name, adventure_path(a.id) %> - <em><%= a.tagline %></em></td><td><%= link_to "Edit", edit_adventure_path(id: a.id), class: 'btn btn-xs btn-info' %> </td><td><%= link_to "Delete", adventure_path(id: a.id), method: :delete, class: "btn btn-xs btn-danger" %></td></tr>
    <% end %>
  </table>

</div>

app/views/adventures/new.html.erb
<h2>Create Adventure</h2>
<%= form_for @adventure do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, class: "form-control" %>
  <br>
  <%= f.label :tagline %>:
  <%= f.text_field :tagline, class: "form-control" %>
  <br>
  <%= f.label :synopsis %>:
  <%= f.text_area :synopsis, class: "form-control" %>
  <br>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>

app/views/adventures/show.html.erb
<h2><%= @adventure.name %> </h2><small> <%= @adventure.tagline %> </small>
<p>
  <%= @adventure.synopsis %>
</p>

<table class='table table-hover'>
  <% @scenes.each do |s| %>
    <tr>
      <td>
        <%= link_to s.title, adventure_scene_path(adventure_id: @adventure.id, id: s.id) %>
      </td>
      <td>
        <%= link_to "Edit", edit_adventure_scene_path(adventure_id: @adventure.id, id: s.id), class: 'btn btn-xs btn-info ' %>
      </td>
      <td>
        <%= link_to "Delete", adventure_scene_path(adventure_id: @adventure.id, id: s.id), method: :delete, class: 'btn btn-xs btn-danger ' %>
      </td>

    </tr>
  <% end %>
</table>

<%= link_to '+ Add Scene', new_adventure_scene_path(@adventure.id), class: "btn btn-success" %>